drop table user if exists;
create table user (
  user_id integer primary key GENERATED BY DEFAULT AS IDENTITY(START WITH 100),
  username varchar(50) not null,
  name varchar(50),
  email varchar(50) not null,
  pw varchar(255) not null
);

drop table bet if exists;
create table bet (
  bet_id integer primary key GENERATED BY DEFAULT AS IDENTITY(START WITH 100),
  initiator_id integer not null,
  challenger_id integer,
  title varchar(300) not null,
  description varchar(300) not null,  
  pub_date timestamp,
  resolved_date timestamp
);

ALTER TABLE bet
ADD FOREIGN KEY (initiator_id)
REFERENCES user(user_id);

ALTER TABLE bet
ADD FOREIGN KEY (challenger_id)
REFERENCES user(user_id);
