create table if not exists user (
  user_id integer primary key GENERATED BY DEFAULT AS IDENTITY(START WITH 100),
  username varchar(50) not null unique,
  name varchar(50),
  email varchar(50) not null,
  pw varchar(255) not null
);


create table if not exists bet (
  bet_id integer primary key GENERATED BY DEFAULT AS IDENTITY(START WITH 100),
  initiator_id integer not null FOREIGN KEY REFERENCES user(user_id)  on delete cascade,
  challenger_id integer FOREIGN KEY REFERENCES user(user_id)  on delete cascade ,
  title varchar(300) not null unique,
  description varchar(300) not null,  
  pub_date timestamp,
  resolved_date timestamp
);

